// tui-image-editor language configuration (Chinese)
export const localeCN = {
  Resize: "调整宽高",
  Crop: "裁剪",
  Flip: "镜像",
  Rotate: "旋转",
  Draw: "画笔",
  Shape: "形状标注",
  Icon: "图标标注",
  Text: "文字标注",
  Mask: "遮罩",
  Filter: "滤镜",

  Download: "下载",
  Load: "上传",

  Free: "任意线条",
  Straight: "直线",
  Color: "颜色",
  Range: "粗细",

  ZoomIn: "放大",
  ZoomOut: "缩小",
  Hand: "手掌",
  History: "历史",
  Undo: "撤销",
  Redo: "反撤销",
  Reset: "重置",
  Delete: "删除",
  DeleteAll: "全部删除",

  Bold: "加粗",
  Italic: "斜体",
  Underline: "下划线",
  Left: "左对齐",
  Center: "居中",
  Right: "右对齐",
  "Text size": "字体大小",
  Custom: "自定义",
  Square: "正方形",
  Apply: "应用",
  Cancel: "取消",
  "Flip X": "X 轴",
  "Flip Y": "Y 轴",
  Stroke: "描边",
  Fill: "填充",
  Circle: "圆",
  Triangle: "三角",
  Rectangle: "矩形",
  Arrow: "箭头",
  "Arrow-2": "箭头2",
  "Arrow-3": "箭头3",
  "Star-1": "星星1",
  "Star-2": "星星2",
  Polygon: "多边形",
  Location: "定位",
  Heart: "心形",
  Bubble: "气泡",
  "Custom icon": "自定义图标",
  "Load Mask Image": "加载蒙层图片",
  Grayscale: "灰度",
  Blur: "模糊",
  Sharpen: "锐化",
  Emboss: "浮雕",
  "Remove White": "除去白色",
  Distance: "距离",
  Brightness: "亮度",
  Noise: "噪音",
  "Color Filter": "彩色滤镜",
  Sepia: "棕色",
  Sepia2: "棕色2",
  Invert: "负片",
  Pixelate: "像素化",
  Threshold: "阈值",
  Tint: "色调",
  Multiply: "正片叠底",
  Blend: "混合色",
};

// tui-image-editor language configuration (English)
export const localeEN = {
  Resize: "Resize",
  Crop: "Crop",
  Flip: "Flip",
  Rotate: "Rotate",
  Draw: "Draw",
  Shape: "Shape",
  Icon: "Icon",
  Text: "Text",
  Mask: "Mask",
  Filter: "Filter",

  Download: "Download",
  Load: "Load",

  Free: "Free",
  Straight: "Straight",
  Color: "Color",
  Range: "Range",

  ZoomIn: "Zoom In",
  ZoomOut: "Zoom Out",
  Hand: "Hand",
  History: "History",
  Undo: "Undo",
  Redo: "Redo",
  Reset: "Reset",
  Delete: "Delete",
  DeleteAll: "Delete All",

  Bold: "Bold",
  Italic: "Italic",
  Underline: "Underline",
  Left: "Left",
  Center: "Center",
  Right: "Right",
  "Text size": "Text Size",
  Custom: "Custom",
  Square: "Square",
  Apply: "Apply",
  Cancel: "Cancel",
  "Flip X": "Flip X",
  "Flip Y": "Flip Y",
  Stroke: "Stroke",
  Fill: "Fill",
  Circle: "Circle",
  Triangle: "Triangle",
  Rectangle: "Rectangle",
  Arrow: "Arrow",
  "Arrow-2": "Arrow 2",
  "Arrow-3": "Arrow 3",
  "Star-1": "Star 1",
  "Star-2": "Star 2",
  Polygon: "Polygon",
  Location: "Location",
  Heart: "Heart",
  Bubble: "Bubble",
  "Custom icon": "Custom Icon",
  "Load Mask Image": "Load Mask Image",
  Grayscale: "Grayscale",
  Blur: "Blur",
  Sharpen: "Sharpen",
  Emboss: "Emboss",
  "Remove White": "Remove White",
  Distance: "Distance",
  Brightness: "Brightness",
  Noise: "Noise",
  "Color Filter": "Color Filter",
  Sepia: "Sepia",
  Sepia2: "Sepia 2",
  Invert: "Invert",
  Pixelate: "Pixelate",
  Threshold: "Threshold",
  Tint: "Tint",
  Multiply: "Multiply",
  Blend: "Blend",
};

// Export a helper to get the locale based on i18n language
export const getImageEditorLocale = (isZh: boolean) => isZh ? localeCN : localeEN;

// tui-image-editor custom theme
export const customTheme = {
  // brand image top-left corner
  "common.bi.image": "",
  "common.bisize.width": "0px",
  "common.bisize.height": "0px",
  "common.border": "1px solid #d5cfcf",
  "common.backgroundColor": "#fff",

  // header
  "header.backgroundColor": "#000",

  // load button
  "loadButton.display": "none",

  // download button
  "downloadButton.display": "none",

  // menu states
  "menu.normalIcon.color": "#2d8cf0",
  "menu.activeIcon.color": "blue",
  "menu.disabledIcon.color": "grey",
  "menu.hoverIcon.color": "yellow",
};
